# Generated by Django 5.2.16 on 2026-07-22 13:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=64)),
                ('actor', models.CharField(default='SYSTEM', max_length=64)),
                ('target_entity', models.CharField(max_length=128)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('device_hash', models.CharField(db_index=True, max_length=256)),
                ('browser', models.CharField(max_length=64)),
                ('operating_system', models.CharField(max_length=64)),
                ('screen_resolution', models.CharField(blank=True, max_length=32, null=True)),
                ('user_agent', models.TextField()),
                ('is_trusted', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'device_hash'], name='transaction_device__aa014c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('customer_id', models.CharField(db_index=True, max_length=64)),
                ('sender_account', models.CharField(db_index=True, max_length=64)),
                ('receiver_account', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('merchant_name', models.CharField(max_length=128)),
                ('merchant_category', models.CharField(db_index=True, max_length=64)),
                ('merchant_risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=16)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('ATM', 'ATM Withdrawal'), ('POS', 'POS Payment'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Wallet Payment')], max_length=32)),
                ('channel', models.CharField(choices=[('MOBILE', 'Mobile App'), ('WEB', 'Web Portal'), ('ATM', 'ATM Machine'), ('POS', 'POS Terminal')], max_length=16)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('card_present', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('country', models.CharField(db_index=True, max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('browser', models.CharField(max_length=64)),
                ('operating_system', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('network_type', models.CharField(default='4G/5G', max_length=32)),
                ('account_age_days', models.IntegerField(default=0)),
                ('daily_spending_so_far', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('previous_fraud_count', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['customer_id', 'timestamp'], name='transaction_custome_bf8a66_idx'), models.Index(fields=['merchant_category', 'timestamp'], name='transaction_merchan_188e17_idx')],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fraud_probability', models.FloatField(db_index=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], max_length=16)),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('BLOCK', 'Block'), ('HOLD', 'Hold for Review'), ('OTP_REQUIRED', 'Trigger 2FA/OTP')], max_length=16)),
                ('fraud_category', models.CharField(max_length=64)),
                ('top_contributing_features', models.JSONField(default=dict)),
                ('human_explanation', models.TextField()),
                ('model_version', models.CharField(default='xgb_v1.0.0', max_length=32)),
                ('prediction_time_ms', models.FloatField(help_text='Inference execution time in milliseconds')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(blank=True, max_length=64, null=True)),
                ('analyst_action', models.CharField(blank=True, max_length=32, null=True)),
                ('investigation_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alert', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-fraud_probability'],
            },
        ),
    ]
