# Generated by Django 5.2.16 on 2026-07-22 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., High Transaction Amount Threshold', max_length=128, unique=True)),
                ('rule_code', models.CharField(db_index=True, help_text='e.g., RULE_MAX_AMOUNT', max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('field_name', models.CharField(help_text='Transaction attribute to check (e.g., amount, country, merchant_category, velocity_5m)', max_length=64)),
                ('operator', models.CharField(choices=[('GT', 'Greater Than (>)'), ('GTE', 'Greater Than or Equal (>=)'), ('LT', 'Less Than (<)'), ('LTE', 'Less Than or Equal (<=)'), ('EQ', 'Equals (==)'), ('NEQ', 'Not Equals (!=)'), ('IN', 'Contains / In List'), ('NOT_IN', 'Not Contains / Not In List')], default='GT', max_length=16)),
                ('threshold_value', models.CharField(help_text="Threshold value, e.g., '10000' or comma-separated string 'RUSSIA,NORTH_KOREA'", max_length=256)),
                ('action', models.CharField(choices=[('BLOCK', 'Block Transaction Immediately'), ('HOLD', 'Hold for Manual Review'), ('FLAG_HIGH_RISK', 'Boost Risk Score (+50)'), ('TRIGGER_OTP', 'Require OTP / 2FA')], default='FLAG_HIGH_RISK', max_length=16)),
                ('score_penalty', models.IntegerField(default=30, help_text='Points to add to risk score if rule triggers (0-100)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=10, help_text='Lower numbers evaluate first (1 = highest priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('CUSTOMER', 'Customer ID'), ('MERCHANT', 'Merchant Name'), ('IP', 'IP Address'), ('DEVICE', 'Device ID'), ('CARD', 'Account Number')], db_index=True, max_length=16)),
                ('value', models.CharField(db_index=True, help_text='Value to block (e.g., IP address, Customer ID, Device Hash)', max_length=256)),
                ('reason', models.TextField(help_text='Reason for blacklisting (e.g., Confirmed Chargeback Fraud)')),
                ('added_by', models.CharField(default='SYSTEM', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('entity_type', 'value')},
            },
        ),
    ]
